site_name: Unifi Docs
docs_dir: md-build
site_dir: build
permalink: True
nav:
  - Home: README.md
  - Contributing: CONTRIBUTING.md
  - API:
      - Stable Coin:
          - IDoubleProxy: stableCoin/standalone/IDoubleProxy.md
          - IMVDFunctionalitiesManager: stableCoin/standalone/IMVDFunctionalitiesManager.md
          - IMVDProxy: stableCoin/standalone/IMVDProxy.md
          - IStateHolder: stableCoin/standalone/IStateHolder.md
          - IStableCoin: stableCoin/standalone/IStableCoin.md
      - Microservices:
          - MintNewVotingTokensForStableCoinFunctionality: stableCoin/microservices/MintNewVotingTokensForStableCoinFunctionality.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - typescript
    - javascript
